export { default as MapMarkerSvg } from './map-marker.svg'
export { default as MapMarkerMarianumSvg } from './map-marker-marianum.svg'
export { default as MarianumLogoSvg } from './marianum_logo.svg'
export { default as MarianumLogoWithTextSvg } from './marianum_logo_with_text.svg'
export { default as WavesSvg } from './waves.svg'
