/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import upload from "@strapi/plugin-upload/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import ceremoniesDebtorList from "../../src/plugins/ceremonies-debtor-list/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    graphql: graphql,
    i18n: i18N,
    upload: upload,
    "users-permissions": usersPermissions,
    meilisearch: meilisearch,
    navigation: navigation,
    "ceremonies-debtor-list": ceremoniesDebtorList,
  },
});
