apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgAd91j29+G4ApcpxV8LXTtlNjzz1XHau9L1lTdfMHQHtleXdm1S3fDV/APcnQqUxf4hcVNj19P2vi5xTUvhwUAkull5xsQOPDPr5lX7ZK+UMDfX3aJS2c0A4EL6SrKTOlhIvwVggMXliotUde8taYGSTupAdYyVutyMsIIzGjK52NrIYy4zLASFWKP00W70YeRmA/xqLAuujtKzp8ds2bzudDNofr0WxI7ApWA45w8n4Uz0Dk7RbfWcCllgrlBOoo0j4qsnRohwc/ywCizLt5ypp0G1cVj1mUjpqbQn6rauzw3JMeQMZ91+cjnDdse4s1keKCcHcayfmGlZU9rukNQReROi+EJXPX3Fi/R5Z2AU1g/uYPKYXgSDNoiSn1Qe71rUz3oiwBX/9+SRfOSKXAaj/IOOHk/3fEnEJA2sFxHJRITYXlMv1V0b6qGsrwwStUBZOQNuO+AGmZAG0iMcInaC75n1Gkl95qnBMcImMv7PrNUgZSM57+3MGolJjaaBWTBgSpr1oijX7eXPO+tU0yL0eVChdOhq3YAjM+ZSbVasjEFiM+UbB+LkvqyeBrhockF5kYrVZon+mcv5Bwi7lFmbsEpZ+fA+KzyjHwM024jvVDryXov32BfG4eHYVjurIbjsMD4WFYrp6oT2DXv8cpGQ7Pd7V/zhtM5Wcl4bu8KPnpljLhznnlqCp7QvrzcAUYAL3xO+rDSrIqrIbhAIERflxmxi/asSUSRSZrEgraJsyvot3w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
      namespace: "${NAMESPACE}"
