apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: marianum-generics-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBsbKKXuQ66a8R/b5EPWT+O/aaebjY+Qhx7KDmOP4Vp+xN8zqvUu3lakYOiKwzGZY25g4EhM9o2eIQDaZ7/HgVZ9Ftifl1mwxwwB9N68lhrYMJ5hjmgN8BsJF/3qrIgcNJ78P8v6Ya6H7Kky/Tbp4s6LoStbctlxW2F9ulwCmOHOmK1gHEo61kEyIMDob56NW7i9r99oyiTCs1Mb6jHUK/5NP9fO5zpwqmWwf8JwEt4yWS/j9iryIh0DHl03VJzyXL+2DI/GFx3SZK+JdqTdTyIXwjvUXbvxbds2NZpmWeCkdAvRmAVRjfpvntwp3Vxa79NT0VTxzgPii3OWUZGxPjpiboK82RandB9elAOh1i3ZJl6IuCfju76q3X2sqVBmIm1XehHkYdeMprOc+8sfn/ij3UOKiHo69+xXJDJJupCgHvtse92LmfP2Ln8YgJG30OLdw3qZ0vzXkz+sjVJKaeExu/QjV2BTmO595aUAnphlTfR7pLV+Ivm4nboAKZ9y31Yo7neWGEYWlr8u/5Yi7MkrhEtqSjBwdG+ZwcFxOvqey0SMmlYh4akuUDeZP+8/TWP0WwOrkKWNdYCtzVnkae37fsPHJ6GNHq653C0ibOUUISVixvqVg0N7O6M4C8sTppiE6jaPBQi7lmT6sE4Iu2Gh8pR534P2sVNqfqDvfJ6YVH53PIjFIwOIyxB9QRNlZwcHgToM8Yy/+Kzl1hUQ/Zw4+kTjcKL184=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: marianum-generics-secret
      namespace: ${NAMESPACE}
