apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgB930eKT6tx2uwOPFRlprlRBh1MI8bHN5WRcDfnSuZygji1J2AA5mDuYNXEbEYDZ+woZ7AfHPgDBpaqCay45d4a+b4Ko+fzg+wUIVEb70wLi+4hvcDn0y6G0bB/AgD4tHtCIYQOobCBTaA9xeXB7nKtwM1HdVey3aHROdjUGTz7jWAQv0vSIOc3bvfvpRnV7J5GJ3rf/jhplclav+43ExKfzzMOCJuzMX7lfW6hXZa0qTXHsYekYYykNZIJPF9PrV/+jImGRp0QU55stvonDweHHR1Act+SYV61LBsb/LzrT7wdj4Rwo/Oipz+pfAqyn8RAijn0HuXFCJHUedSApnYUndIc1gxe/oXYYQHsRMESrD/W6RL9xTk/TavdXnJRdC1uVHJuQ3MWVtDpr9I+j5rHnXACorWJXpqErZxnjZsdZDD20mPStZlucAoQbXW6jxP9OhX46ctJpdtbzDMwBY4BnlwLD9VD0wMJ9qGs+2rXRYnleZZzosNNPU9amtju7CHmolPt59zKQauE9IhB/ggAQ3ZlRXBqg/3bDlFUgXEbEqoAXPnO5etigqjf6tYO/p8NgVohX2EnnVXn0A0pbIC6DSFyhQ/UWAw9wyJER1+p26qrK8kBVf6Ytyjt8UVeDxf6pCZpJiXH6Lw7qFyFYc8datr4592Qh3dXAzjZ5yEXvMnJjRvCfr5WIi0FkDwwjfQwxQHMD/lCnJ/jE34R/+swevpAyzX6Tjz5KNmDDYNMAJsgZscM6QK2faLEZ48byElPwg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
