apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgAsKUNR202VzLtlbvqRLfYY+FLSWSUUxcpOAGLG9TN2VZj5KQSaSywZ/AgSqyfv82hKDRUUtNufaAEjGTtYC18n89UTL7MI/BjnDP1U3ITlWA3z0gY6st/xQXKORaz4NUlo4y7GYRQqtyOXUy27YopzMIqJYuv89kRfaDRXZrfvDbKFzGFyDWr7g0gzIchgudWRGEqrWC5hbZzh9+AbIlLRdntRS045xcTyyKAWyT7Tv6gJzq3oOXBwNAABWcLwaRGtTaiyLISgQLxb9tv07ceXa5s29qmvBHdW7AZ7Lz7uBzsRVlB2jc9krEsYKT0lOS37e/mkCy9ietcTmo9La2HCPniI3/ScTmqirX9nXlEv14cMLgZxt5rHyK0jUw7D9lGCtruVB4cRJvq4UM5pPmmogzja7nf++d9oPWXtAaKiXoRK4CqFQtkmsbQlJOx4k16mrF796UOIigWpkfcZ5VpnnfBFPNwrrZ72jyHK2NizCOJUuxl9GiKjdhqgX0SjJnTTShWJ08VuxBJBg8u2GXm+GSU4x582nn9GL853JPZF2wWjgCMlrvYHWC1wp6418s1AzscE/OVL+//VFuaZiOl7XHTrXF580lORmpG5evEIgjcNBmESW+hFRKy3EYy/SUQ+FixApjYF1ZW9TU9GVFn5LtWc86YQY+6RACrIrQzeT67SsVEkaHZaSfk14k5Db3bsGKXsALObJN3LPRcYmshMjMu5hXejK2yKm+x5gC2J
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: "${NAMESPACE}"
