apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgBt+xVyb4ZZk3cAIgzUrHrzz6qfiW+Mjk/IwrK109l7FPUGjSLaBo6fiITT8D6fUWVGtmyaX+w+9Ovua8I4/BWWFJ8RTAwlZunfvES6lFAgLrAVIMrEy25CEa4DpRYeZPJQPZBW0p8NyzVJInVsOdq4+sHyW4wLhLLJG6/zrQs60Qgia8SqeW+LgkemBE7yh63u9hJQTTrntcyWrVVqDS95QxCwo/9qnHwwvb7+h905XppewuiEFSeTdWfkUI9uEHgRVElqHXs+nDaOJx87JsLHh2leE8jmP+JPJ27TM+//4o0AlUBw2o8EEvNwF0fz8w4jqEISdVYTQZ1vJhMIBemyoX3lado0e6U6WipivMeH/zutb+IbjKRU0AH8ZY3nFcbgA18gXLuzWf+v/Gu7/4YeUBlrWwXc4ECYvbK4eNXfZrnZjnCS50j/PwvbkZ/wllDv3AfkZILlvcR5URp6T1+1ugjpzRMeLodK8loNCR0SotnEl8jPssiR5AP4+OyB4Jz4n9ENhnqCMZeCpCewhwNPxE/8byD/S2oOale0pUSRDLr8i6KjTxghvb7ToZdsIf93H5wDkk5SJa52hwvM/7g5CUGqUQlXQyblMu+ckUWH1TDQ8lzTJYe/oWAaTdQ969OqHwrTdVokbqE8v/r6biV+sCcsONlMNqU7CrLpYUwZnd0H/ZXbOJZots4kd0fUXTmnGLKlylvL2P+tBHF4+GYtKFck+WY5Zj/5GrzlHjS7n29bnA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
      namespace: "${NAMESPACE}"
