apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgArgOFsB+w0cv6y/nRttragpDs8mVpX1sOgnX2I9UMjGdsrurPpCu92tsHFzh7UQBw8gnD9WglGwFbFPeiCyIFlW0Xr0J3e1rB8iO4KiCLeeKNhN+PD8sekYghPwe1hdSL+jmMuKqiQ5iEYejwGXXVw+QGt8wtbciCYKtA1yhWLVBA89NsAWoVdfbRxvscDWJLtpUEAFjqaq7H145I2T6p31CZfkPWP5sNrm3DF61LTd8CFggvBTiYGQezmsEa9Epqu0dV23rOpdkqHS94TfHrG5kgCkoChJZ8zUZ0mkJvkEhaInFnzthV+WfzgB8ZFezOgZMgZLWR3iNkihfeGQajkI0CdHQwMQOw05H80KmiM6064nkwrySSUOvOvInDpP5NP5qPO9PlzQ6xF/I7DoFG5N9tv8vMnelZdAlm4A3DcelWF35Fo6sk2iRKiEFr1UguFG7ktK6kWuwr1durI8pCH7B5Ur6LywArRJE6SZOWn+tTRfj/NGvHNPQ2YEONdRb4cADWAY0kK97374yUqhGcUCXo7WU7GNnBz2H9cTNibhxY1yMm9IOODeB3DQSLN9LVCQZVu51aoraW5tuH2+h9yK6aDjfSHV+K4IrEv5ead6+XD2sR3NfDhcXOQ8p0jZkiWQ6cZa1+Eebv56XLLgWmuSL+tpZ1p7mKwqV6r7+KT0dCb2wXL+YykdQeblT1ezScs0gQ8Xoy/Qgasolu78hqqzZeRbn1CqI4M/k4QASoeAg==
    POSTGRES_PASSWORD: AgBbK8imNklrV0hA/ZBHx89mUV9nfOl20jcQdmG39y9ci+422FkaQCC45ZrrwJnI1toKGKDAbdSGRLmTKLXGFxcshc5j2Tcqs//r96/8+UXra24AX0d/m4sxPSb1YFiCIRY/YajSM/E+YRQeV6pBJXluho5LCVrcVBF1rdvd4ZU4eiaeBb7yroULNuD89cM4CQ9nqDZiUbbGJNhtcojcCMYSKZJ/5m+6SK8waOrwXm1xfz6uQMyP4GLP2Vsh/xft0EXv3U0KaH+FsBPIpLfK4U8gHL5txBn30UyBqA5xBPSxa6iBuJWgwjO3lQQP/OxRVlsIf0Vesp7AaCwLoBjOqFs89Hs8tSYtCL62xqhRSRZkIC3ktA/jz9iOXcKRar2YkqvB4rpsrDDk/Xv9AgFRzF63/iwFsMDY7zyP1dM7oBeDHgQyGbUOafngJjf2fR9TJUyopgJXOGUb2pXA36oN0olHg7Xx1pjhQ0O4qYgwS74DwwoCHfReoevEUJC8npMmXRtDodmFq17szL1Q6o2j5mKu+kzFlWPSip7fhdQ5uXazdBNPGWFAUwpXzi4xCJ9FEvVZaOE5Og2wKuaRUU+1t2P14lfX+BjlSfwgKqJXx6tpyws1AUZs6SpIjP0Nz+G0UoIsqjAw0E2VGEcivCslFN6jeiJ0P8VsRwYM5WkMXMvcaAonpHOghyKnP8g3rFlZGPNBGcL98ECM8qoIjbEPEgXJiWXh83T9Edrjb3pTr0x61A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
