apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBTaHtNFoSaGb4LaEZ3Re3n/pFM2zoq02B7ZchQOqSWk7K4+NC2Zn2sGAlgi3zlg26ki50QTBQl3LbsN3EhZCr+0Xs1p/AflTJb0dsW/Dv/xbalVi30kgPQZK1KBSq7Zh0d80lxzfeKG5023lu5xj/TIcE6u48o8q0ptIIYVzN2+qov/xAsSfvQdGeLhu6st63whx55CDSfL8j2YT3D1F+eET9aOFTRpa113BA5sGdh/0SqxItQ9IBBh/qHVT8seFzBB97qCu9pGR8gHWxY1wCW9OBrPBnax2LfT36RT/WjC51MMq8NPKknE9M2Y12eYPeCbj85j1ffLqwyWDT6HDGAE/xwsq76aIVoKRjfqQo+j2ML9BRxQpsBMGunocd/g+RebWkZVqagecATWn0S1sjrLDsTZ96BGw+Jwuu/+6D7+OglC890DfG5Ls+LpOTbNkp1otbuhQCF1b35ImwZfAdpwybNOCbCN1dOCAn+L4xjtbkGBrK2J2IfoEKOxeTD7E8LlgAa9U2OfPfsbmDcl+tjQgJMfcDnOcI6qzK4BtTL5MVmqpNNooGD67IhWddjTrVgwkjGj+mvS/454l7P309aSEPln/P8KRJRYzPzEm+m9Ob8Ery/8a4DqX+PzwH21o50GDj0W+75oi7FKt8uBOpLD0DJhZ0EzO3cmzUu3krQF/6rKzlK0iVdS8iftwE7arSsMLJGhDrNoYc5ioCYJQMCyQecNCl0eExJkolVCQsqZQ+2gZdA6zkoXA6+yDMMZ+sfXw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: "${NAMESPACE}"
