apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MAILGUN_API_KEY: AgA2F7AqfsTIY+vK6rvkS52i5O2B3DLrG234X7cJeEiEl1P3MQKO1jI4U8SSNJt7UA4EOhOTnedMKktfv7TYeKHdMIh0oq8rnac9MwUcemOuJiPQJhGuQTDqprZ8Oj6Cy2oYKJGS9eLdkydBQ1sgzxcu0yc9ih9Z8SGbElXxA4LvjXOnszzmt42Zkl5gsWwycEuxESIlvtnsZ8z8lgleB2yLil73WCF79nP1nIouOJ9hGjvclmYFsnMmTqNGhJ4qiGfHx6YMi8K/a6F6D4QCMHic1Q6bKuPm5pd6ujyDWLynoaQq9jnzBP844xnLp+ovO39xdfm1ypwwbXAzlbBSwdrEQpILaecTPqoxJoh9EzuWtid6bztAQ4QqHXkrQf61ZSHCYF6OEGFw602skhnhSEEMpplvkdZE7jU8OiuplJdLBSDQsIJPCeeQKKUV5HiWgbBhG0YX4qLpIp36TzRMLovsvsBN3Gr+7Z7hKf/GMX92+1t4Jgm+jYcNbweNY1QMbkoovANRh+pizrH+Z7icQk6R5iu0jN49SMF/Auiikb3aH4zJwGfTNGIRbTnndf16zSUyx6ucvzUVLSg7W90njsXI475iqKzGIZQYd5+wGQPywoV7DihgoiwNohjgstrFmOHDH5QJVnkSzL1VB+5gvusAQzhmCRUv9NlFgpahzZut7P3FW4AC9raEAB+7d8OpirYHuruj6wADYxT1ShIRwkUb4FwROFAeeco+jy4tFDFsBqHyOoAtpllVZS1GxnmA17gh0Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: "${NAMESPACE}"
