apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCoyDwY8astSS53u026W9ThebLDMkBo3Tc5zaQ94oxUsOLMT47grnhHtG0xIOI7kfyAICYZXRimWbKIngZLPFUv/K0oZj4hSg5geqEPqA5KKtNh0g5Uec2iiahuyuMX/GGwkQSDf8gG92Q8uZFBQltVq1IM1H9U+MMRQsFEzNQ3eDCb4TMgclpc9ndx9FN9kRXbhRQ5oaanuAtHTa5H0+PS5ILhgkIinCtg4ddNJHDOEidQYvrBVOV1IMf9WOz8YqmgSvIP58vzLLz1j5lcJRTqwhqk0lfS5p/l67PN1xjGOJeVn7t1CmHGwkDzJ5mhguYrGH/Z3yJPpynE8b9W2zx4Tb6yEgqH94htSwnQgBqQ05jU2QdoFBQSbSWhC3UqCsKjVtidNiBs3tZi4mbN2zzcXa3UkRrxYV6YXDs94L8SZS6bJfl7hT3ycONWEO7wMSuapqHlkpk1BJwm8NPevEWJYBSV0eYK6m3eH8zh3QMne2u4egGnNB/4lGuT53Ka9ah/f5QFQmiDtVkaANYD23H0JIy1XgRSGEFofE1znbrKfeimwfbVD76wbLVN8ijNmPzR/TFP9pu/KgMGcsvTAGJIbAk5SkoIXy1GLJkoBbR8EV8usapgv2PALnJhtTedLWrJL1wIo2u4ThglwinVTVIDQ7KULk1D7tbbnyyN/tIlkp9/r+Zg7FrRulyQAUDW2h4mNTf32adFTQ==
    MINIO_SECRET_KEY: AgAj/JW1Nbsx3Qq8plz7AMDXGbjxivIWzYb+V7zE1U4pihTiBqBR6/qUhkqailfSZcq989QTKPLT2bN1a6ktikFpzu8huYHv+z9tGz2hXd4rivIO5HRi05ijK6wPPpnoF5Z6jqAe3F/fs//AECqPeshCS0ij/z5Evxr+rEJRAwA5gJCkXxHtb/eHso889KydRaGgSFFn3KtdCAFwPn8DIQQ+jfyCCgAOr3qKFuYLmo7IB6hvlJx/K6xXiiwARfCNiY2/f0yK+8LDGW64x9FkvyHobbrO/zHWUL5Os7l6pXLL1PqjLGYLm4rw+I+U+E3RyC5S5AL4YVPgVGxcSQktA0LDGC3h7DIF2aBd1zY/kfOZ4EXwSIFDfTIk1h0x2IjR+Cg4wwXHsEIUcW45L4w7Uu3hYJ9YEif+C4c7N2wLqwJJtk72ADMbF8ov1pHmM8vdLms63D4sFXqVFlxcHh5pF2c8AJtf1lNQcPkAQcwvgTjTrLlOKj65fqS6k64PD8nClyYMgzYkdywyDeUTGKKAYK3HFH7BchUgZbkrC13EbhH/AnSzfv0fNH/L9yqCBeVPeRJxvHpyYzVvmYRFQvz+KoqKev377zJJmRVDNmkkXZ44NeXcjyRfA/cSZd+szP7wJotaYdr6rBy+0T4l7zObpZq7/t3jILWku5MXkAtXcGAizhnujXJdPQJRoMWGa8JyIbo9VAYGs4g7URTKBbtWuOAri7z+RMk35FU8TL/yosxlYrwzE6kDd8/Nh9FgrWqllJuwQTlLYGC3dg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
