apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BUILD_REPOSITORY_NAME}-app
  namespace: ${NAMESPACE}
  labels:
    service: app
spec:
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
        - image: ${IMAGE_TAG}
          name: app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 900m
              memory: 8Gi
            requests:
              cpu: ${NEXT_CPU_REQUESTS}
              memory: ${NEXT_MEMORY_REQUESTS}
          envFrom:
            - secretRef:
                name: marianum-generics-secret  # populated by Strapi
            - secretRef:
                name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
            - configMapRef:
                name: ${BUILD_REPOSITORY_NAME}-env
          readinessProbe:
            httpGet:
              path: /
              port: ${INTERNAL_APP_PORT}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: ${INTERNAL_APP_PORT}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
