apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAwNOlg4hYp1+i6G8Exj+i8m33MKnUMW5x7eKsEo1+zACC1wlucDk6PXsw+B7y7BsTWp3C7nRLl4zTAuhNEK09CsKojLh760L7U5fQdeqrE3wlVau+z5mThlhdcknE5xGemE0B043KS/4A0oMyhLja+u5AxnOOcQWQzyXxftuTfAF0wk5yK5vg83HR9HqoDY5v5D0KTYaG6HoA6P6299pYMCbPrJW9PWLCWCSaiLPuS0nbY3BQMvSsJGcp/EuAXmrb6ENQ3ndixsFIcZRCfAbE/lLi7irC+87ptZwmUUwlrE+bOPRS50Av5fc4VbHQlb37kBRv9MMiLJy2efL9EWik7AhNuMBvHaQRLInYeyTg63TxHfXF6ZgKt/WYXGxbV9jL4NF3HHO4gKSXbRC3Y7Yky4S0pfIwzJImwcKZl3P3rfKmz2Ds0zckpxlyrLQoctCHmMLHELfoRRaC5QQMfid7ydmV+1QRuBL6hJKERY+kCDwDPU2FKeSxlv8Rd8uEO2YdFMqkQlmIk4/kLHJXiqFksTc1yenuRx9IZJMvoEVpG85iYtrNCuX+istbQ96i0eSX4ErDJpNIC1YT7EW2+DBHEmTzraS8xrhdXQOHq4D7JOvY3X8C0Op02DjN7o6jZFw5m7Jg7aiprwkG4GzefdpRbDjXlofWitL95LQe6au+goxq61snsKxiNv1U57vJ7rzuYz7mjvmFrb2R3EontyS3ayT4K1lLaF7x83ltugxlW
    POSTGRES_PASSWORD: AgBecRrV7x8jkB9FRjFyCO/TxEUsG4m4iwQyasqQ/MFPVP4YHiiYpdCH2slIL0WjPaVK5iF+2qTRH3JlPWY89NjXcDTyv8iqrfBxZqd+cacZlKwxWcErbkrPy04EXiLF0/enp2O5LKe/UR+Q3t4gvWtIdA7TVB6Yz/g0uV9uLvevqCGNvIn1qichauxbU2wKDnwvBXH3fqLDmZy5WGRCE1vgQhjJiMvwuUyrd7cTTUIZyHicUuIJZZGfx4Rt0fCS+EjeKiih9ag1woaXERP/gmFOdPN2rS+xBfFYfWY/ft1YJ57lMUsjXjparaG4pbFwy7+tv9FJeu23Z1M1XVnqK0tALDxLV8HcXOueBV+dfRA16nfCe8Hb2ZQ/Fz4TeSf2/4tgrlbWXFvnDBzFiuvQJHuqsj2g/L501egY17VhEYzEyh9iYPTqroeg5R70VYYMhqrVYGfiTYJQ5lEt1OXj5Wj8WkcyzxjJ+v1+5xLVgKCDVZkKB/SFKtEY+mGUZFOr1w6oxDrDgzYrQf7n50D028bJmavPLeqWs8XXr1jt4icXVLGUwEL7q2BpLbRqFIAHndbeHraLwpWUMeIgDlaQS3uB8ZUN5lNxAmgmw+i1/bdSLQ9YWRPtxqb7+gtN0UZ4NqvTGgUQt+bEhObISgVX3H0pRZHEWr2279f/GbwJm7Zc7qGpd/cP2Z4Yq9KPTIBIxFhiDVEEWo/Huz8AYxcHOFdPGLkSRKAUAwNQ+TGv3L7G
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
