apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAbpMDbtmk5oLqxtS/D1kBMeAfARQ8uoaB6GBu5CHmc0oPT4SzTY1ikwUyOAAQBCcNAbALqUBuusPAPbNIs3mDqp3s7NRQR/j4TTpdhWFw+yecMjtdUEnMV/3DE7N5KRO/cqfKKrsQXZEFxUmQnJwLtJnQixWA7Br0nAZcUyVM8p8iH8O2rSghId/BMeCUbRB/247b6j+ppOxQaisSj7XNdZHWTDlIgr0H6gYDwplQH951scXjps+oXKj3v3lNOUWtyGqrkk8GEXLpveVUPHJCE0jtDjdrukTiCLmQu03onT7etdLkbN2yVGdqolxlhCXMtjuQWahyqYW6ZJety2cy8ClmRToaU/htRy6Q2cixFnH7sL0PpoV6YTggEtYeSJZ2ki0SVnOws/5ivIte2LYEMHZb4r3CukaqGJ+qCI/NdW0HUTOzAbZShK0RmRLFqU51PLvAztihNoBat+uSZBT7UNrWHPaeZR4hWUQbb7IaLUN/rwfrABnNKyQLxuyfCg4rHWzmtMgQ8oCck45vR61uCsHt5W3/i3aQNnPctH2vmvvaRX55Wkl2U9Ou18cEkdjdcDojtTFaBhSOFhslbSguJm9mtpyvFUT/yNeQle9QLNegbs0ey55x+MYtmB5ywME6nPn+JkIzyi/VrsfWMKhpSkfErla+VzfxgkeFVXGUOLcesXypO1NKIGDI/va2XrGmucw/J5rv89Grhhp8H+iiAvyPmkTgSZslH94wgsPbzfqkaqwuVvD+iMVfY2tAJ/LOv1w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: "${NAMESPACE}"
