fragment FlatNavigationItem on NavigationItem {
  id
  title
  path
  type
  related {
    id
    attributes {
      __typename
      ... on Page {
        title
        slug
      }
    }
  }
}

fragment NavigationItem on NavigationItem {
  ...FlatNavigationItem
  items {
    ...FlatNavigationItem
    items {
      ...FlatNavigationItem
    }
  }
}

fragment CtaButton on ComponentBlocksButtonLink {
  label
  page {
    data {
      ...PageSlugEntity
    }
  }
}

fragment Sidebar on ComponentBlocksSidebar {
  title
  text
  ctaButton {
    ...CtaButton
  }
  contact {
    data {
      ...ContactEntity
    }
  }
}

fragment Seo on ComponentGeneralSeo {
  metaTitle
  metaDescription
  keywords
}

fragment Cta on ComponentBlocksCta {
  title
  description
  button {
    ...CtaButton
  }
  image {
    data {
      ...UploadImageEntity
    }
  }
}

fragment Header on ComponentGeneralHeader {
  faqPage {
    data {
      ...PageSlugEntity
    }
  }
  contact {
    data {
      ...ContactEntity
    }
  }
}

fragment SocialItem on ComponentBlocksSocialItem {
  title
  url
  icon
}

fragment Contact on ComponentGeneralContacts {
  address
  openingHoursPage {
    data {
      ...PageSlugEntity
    }
  }
  contact {
    data {
      ...ContactEntity
    }
  }
  contactsPage {
    data {
      ...PageSlugEntity
    }
  }
  latitude
  longitude
  navigateToLink
}

fragment FooterLinkItem on ComponentGeneralLinkItem {
  id
  label
  page {
    data {
      ...PageSlugEntity
    }
  }
  url
  targetBlank
}

fragment Footer on ComponentGeneralFooter {
  title1
  links1 {
    ...FooterLinkItem
  }
  title2
  links2 {
    ...FooterLinkItem
  }
  title3
  links3 {
    ...FooterLinkItem
  }
  title4
  links4 {
    ...FooterLinkItem
  }
  bottomLinks {
    label
    page {
      data {
        ...PageSlugEntity
      }
    }
  }
}

fragment Procedure on ComponentGeneralProcedure {
  title
  steps {
    id
    title
    description
  }
  downloadFile {
    data {
      ...UploadFileEntity
    }
  }
}

fragment AccordionGroup on ComponentSectionsAccordionGroup {
  id
  title
  accordions {
    id
    title
    content
  }
}

fragment BranchGroup on ComponentSectionsBranchGroup {
  id
  title
  showOpeningHours
  branches {
    branch {
      data {
        ...BranchCardEntity
      }
    }
  }
}

fragment PartnersSection on ComponentSectionsPartnersSection {
  id
  featuredPartnersTitle
  otherPartnersTitle
}

fragment MapSection on ComponentSectionsMapSection {
  id
  title
}

fragment BundleListing on ComponentSectionsBundleListing {
  id
  title
  description
  atMedicalFacility {
    title
    bundles {
      bundle {
        data {
          ...BundleCardEntity
        }
      }
    }
  }
  outsideMedicalFacility {
    title
    bundles {
      bundle {
        data {
          ...BundleCardEntity
        }
      }
    }
  }
}

fragment ContactGroup on ComponentSectionsContactGroup {
  id
  title
  contacts {
    contact {
      data {
        ...ContactEntity
      }
    }
  }
}

fragment DocumentGroup on ComponentSectionsDocumentGroup {
  id
  title
  documents {
    document {
      data {
        ...DocumentCardEntity
      }
    }
  }
}

fragment CtaSection on ComponentSectionsCtaSection {
  id
  title
  ctas {
    id
    title
    description
    button {
      ...CtaButton
    }
  }
}

fragment ManualListing on ComponentSectionsManualListing {
  id
  title
  style
  showMoreButton {
    ...CtaButton
  }
  pages {
    page {
      data {
        ...PageCardEntity
      }
    }
  }
}

fragment NewsListing on ComponentSectionsNewsListing {
  id
  title
}

fragment CeremoniesSection on ComponentSectionsCeremoniesSection {
  id
  archive {
    title
    button {
      ...CtaButton
    }
  }
}

fragment UpcomingCeremoniesSection on ComponentSectionsUpcomingCeremoniesSection {
  id
  title
  showMoreButton {
    ...CtaButton
  }
}

fragment ArticleListing on ComponentSectionsArticleListing {
  id
  type
}

fragment ReviewListing on ComponentSectionsReviewListing {
  id
}

fragment ReviewsSection on ComponentSectionsReviewsSection {
  id
  title
  reviews {
    data {
      ...ReviewEntity
    }
  }
}
