fragment FlatNavigationItem on NavigationItem {
  id
  title
  path
  type
  related {
    id
    attributes {
      __typename
      ... on Page {
        title
        slug
      }
    }
  }
}

fragment NavigationItem on NavigationItem {
  ...FlatNavigationItem
  items {
    ...FlatNavigationItem
    items {
      ...FlatNavigationItem
      items {
        ...FlatNavigationItem
        items {
          ...FlatNavigationItem
        }
      }
    }
  }
}

fragment CtaButton on ComponentBlocksButtonLink {
  label
  url
  page {
    data {
      ...PageSlugEntity
    }
  }
  article {
    data {
      ...ArticleSlugEntity
    }
  }
  bundle {
    data {
      ...BundleSlugEntity
    }
  }
  branch {
    data {
      ...BranchSlugEntity
    }
  }
  document {
    data {
      ...DocumentSlugEntity
    }
  }
  cemetery {
    data {
      ...CemeterySlugEntity
    }
  }
  managed_object {
    data {
      ...ManagedObjectSlugEntity
    }
  }
}

fragment Sidebar on ComponentBlocksSidebar {
  title
  text
  ctaButton {
    ...CtaButton
  }
  contact {
    data {
      ...ContactEntity
    }
  }
}

fragment Seo on ComponentGeneralSeo {
  metaTitle
  metaDescription
  keywords
}

fragment Cta on ComponentBlocksCta {
  title
  description
  button {
    ...CtaButton
  }
  image {
    data {
      ...UploadImageEntity
    }
  }
}

fragment Header on ComponentGeneralHeader {
  faqPage {
    data {
      ...PageSlugEntity
    }
  }
  contact {
    data {
      ...ContactEntity
    }
  }
}

fragment SocialItem on ComponentBlocksSocialItem {
  title
  url
  icon
}

fragment OpeningHours on ComponentBlocksOpeningHoursUniversal {
  days {
    label
    time
  }
}

fragment Contact on ComponentGeneralContacts {
  addressFirstLine
  address
  openingHoursPage {
    data {
      ...PageSlugEntity
    }
  }
  contact {
    data {
      ...ContactEntity
    }
  }
  contactsPage {
    data {
      ...PageSlugEntity
    }
  }
  latitude
  longitude
  navigateToLink
}

fragment FooterLinkItem on ComponentGeneralLinkItem {
  id
  label
  page {
    data {
      ...PageSlugEntity
    }
  }
  url
  targetBlank
}

fragment Footer on ComponentGeneralFooter {
  title1
  links1 {
    ...FooterLinkItem
  }
  title2
  links2 {
    ...FooterLinkItem
  }
  title3
  links3 {
    ...FooterLinkItem
  }
  title4
  links4 {
    ...FooterLinkItem
  }
  bottomLinks {
    label
    page {
      data {
        ...PageSlugEntity
      }
    }
  }
}

fragment Procedure on ComponentGeneralProcedure {
  title
  steps {
    id
    title
    description
  }
  downloadFile {
    data {
      ...UploadFileEntity
    }
  }
}

fragment ArticlesManualListing on ComponentSectionsArticlesManualListing {
  id
  title
  showMoreButton {
    ...CtaButton
  }
  articles {
    article {
      data {
        ...ArticleCardEntity
      }
    }
  }
}

fragment AccordionGroup on ComponentSectionsAccordionGroup {
  id
  title
  accordions {
    id
    title
    content
  }
}

fragment BranchGroup on ComponentSectionsBranchGroup {
  id
  title
  branches {
    branch {
      data {
        ...BranchCardEntity
      }
    }
  }
}

fragment PartnersSection on ComponentSectionsPartnersSection {
  id
  featuredPartnersTitle
  otherPartnersTitle
}

fragment MenuListing on ComponentSectionsMenuListing {
  id
  title
  slug
}

fragment MapSection on ComponentSectionsMapSection {
  id
  title
}

fragment MapOfManagedObjectsSection on ComponentSectionsMapOfManagedObjects {
  id
  title
}

fragment BundleListing on ComponentSectionsBundleListing {
  id
  title
  description
  atMedicalFacility {
    title
    bundles {
      bundle {
        data {
          ...BundleCardEntity
        }
      }
    }
  }
  outsideMedicalFacility {
    title
    bundles {
      bundle {
        data {
          ...BundleCardEntity
        }
      }
    }
  }
}

fragment BundleListingSimple on ComponentSectionsBundleListingSimple {
  id
  title
  description
  bundles {
    data {
      ...BundleCardEntity
    }
  }
}

fragment ContactGroup on ComponentSectionsContactGroup {
  id
  title
  layout
  contacts {
    contact {
      data {
        ...ContactEntity
      }
    }
  }
}

fragment DocumentGroup on ComponentSectionsDocumentGroup {
  id
  title
  documents {
    document {
      data {
        ...DocumentCardEntity
      }
    }
  }
}

fragment ImageGallery on ComponentSectionsGallery {
  id
  title
  medias {
    data {
      ...UploadImageEntity
    }
  }
}

fragment CtaSection on ComponentSectionsCtaSection {
  id
  title
  ctas {
    id
    title
    description
    button {
      ...CtaButton
    }
  }
}

fragment ManualListing on ComponentSectionsManualListing {
  id
  title
  style
  showMoreButton {
    ...CtaButton
  }
  pages {
    page {
      data {
        ...PageCardEntity
      }
    }
  }
}

fragment NewsListing on ComponentSectionsNewsListing {
  id
  title
  showMoreButton {
    ...CtaButton
  }
}

fragment CeremoniesSection on ComponentSectionsCeremoniesSection {
  id
  archive {
    title
    button {
      ...CtaButton
    }
  }
}

fragment RichtextSection on ComponentSectionsRichtext {
  id
  content
  button {
    ...CtaButton
  }
}

fragment ProceduresShortSection on ComponentSectionsProceduresShortSection {
  id
  title
  showMoreButton {
    ...CtaButton
  }
}

fragment UpcomingCeremoniesSection on ComponentSectionsUpcomingCeremoniesSection {
  id
  title
  showMoreButton {
    ...CtaButton
  }
}

fragment ReviewListing on ComponentSectionsReviewListing {
  id
}

fragment HomepageReviewsSection on ComponentSectionsHomepageReviewsSection {
  id
  title
  showMoreButton {
    ...CtaButton
  }
  reviews {
    data {
      ...ReviewEntity
    }
  }
}

fragment OpeningHoursSection on ComponentSectionsOpeningHoursSection {
  id
  title
  offices {
    office {
      data {
        ...OfficeEntity
      }
    }
  }
}

fragment CemeteriesOpeningHours on ComponentSectionsCemeteriesOpeningHours {
  id
  title
  showMoreButton {
    ...CtaButton
  }
  buttonPosition
}

fragment IframeSection on ComponentSectionsIframeSection {
  id
  title
  iframeTitle
  body
  url
}
