fragment UploadImageEntity on UploadFileEntity {
  id
  attributes {
    url
    name
    alternativeText
    caption
    size
    width
    height
  }
}

fragment BranchEntity on BranchEntity {
  id
  attributes {
    title
    slug
    type
    cemeteryType
    description
    contact {
      data {
        ...ContactEntity
      }
    }
    medias {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment ContactEntity on ContactEntity {
  id
  attributes {
    title
    name
    email
    phone1
    phone2
  }
}

fragment PageCardEntity on PageEntity {
  id
  attributes {
    title
    slug
    publishedAt
    perex
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment PageEntity on PageEntity {
  id
  attributes {
    title
    slug
    publishedAt
    layout
    perex
    ctaButton {
      ...CtaButton
    }
    sidebar {
      ...Sidebar
    }
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
    sections {
      ... on ComponentSectionsAccordionGroup {
        __typename
        ...AccordionGroup
      }
      ... on ComponentSectionsBranchGroup {
        __typename
        id
        title
        branches {
          branch {
            data {
              # TODO replace by fragment
              id
              attributes {
                title
              }
            }
          }
        }
      }
      ... on ComponentSectionsContactGroup {
        __typename
        id
        title
        contacts {
          contact {
            data {
              # TODO replace by fragment
              id
              attributes {
                title
              }
            }
          }
        }
      }
      ... on ComponentSectionsDocumentGroup {
        __typename
        id
        title
        documents {
          document {
            data {
              # TODO replace by fragment
              id
              attributes {
                title
              }
            }
          }
        }
      }
      ... on ComponentSectionsGallery {
        __typename
        id
        title
        medias {
          data {
            ...UploadImageEntity
          }
        }
      }
      ... on ComponentSectionsMenuListing {
        __typename
        id
        title
        slug
      }
      ... on ComponentSectionsManualListing {
        __typename
        ...ManualListing
      }
      ... on ComponentSectionsNewsListing {
        __typename
        id
        title
        # TODO
      }
      ... on ComponentSectionsRichtext {
        __typename
        id
        content
        button {
          label
          url
          targetBlank
        }
      }
      ... on ComponentSectionsProceduresSection {
        __typename
        id
        title
      }
    }
  }
}

fragment ProceduresEntity on ProcedureEntity {
  attributes {
    outsideMedicalFacility {
      ...Procedure
    }
    atMedicalFacility {
      ...Procedure
    }
  }
}
