fragment UploadImageEntity on UploadFileEntity {
  id
  attributes {
    url
    name
    alternativeText
    caption
    size
    width
    height
  }
}

fragment UploadFileEntity on UploadFileEntity {
  id
  attributes {
    url
    name
    size
    ext
  }
}

fragment ArticleNewsCategoryEntity on ArticleNewsCategoryEntity {
  id
  attributes {
    title
    slug
  }
}

fragment ArticlePressCategoryEntity on ArticlePressCategoryEntity {
  id
  attributes {
    title
    slug
  }
}

fragment ArticleSlugEntity on ArticleEntity {
  __typename
  id
  attributes {
    slug
    newsCategory {
      data {
        ...ArticleNewsCategoryEntity
      }
    }
    pressCategory {
      data {
        ...ArticlePressCategoryEntity
      }
    }
  }
}

fragment ArticleCardEntity on ArticleEntity {
  ...ArticleSlugEntity
  attributes {
    title
    perex
    publishedAt
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment ArticleEntity on ArticleEntity {
  ...ArticleCardEntity
  attributes {
    content
    mediaGallery {
      data {
        ...UploadImageEntity
      }
    }
    seo {
      ...Seo
    }
  }
}

fragment BranchSlugEntity on BranchEntity {
  __typename
  id
  attributes {
    slug
    locale
  }
}

fragment BranchCardEntity on BranchEntity {
  ...BranchSlugEntity
  attributes {
    title
    address
  }
}

fragment BranchEntity on BranchEntity {
  ...BranchCardEntity
  attributes {
    description
    contact {
      data {
        ...ContactEntity
      }
    }
    medias {
      data {
        ...UploadImageEntity
      }
    }
    navigateToLink
    latitude
    longitude
    seo {
      ...Seo
    }
  }
}

fragment CemeterySlugEntity on CemeteryEntity {
  __typename
  id
  attributes {
    slug
    type
    locale
  }
}

fragment CemeteryCardEntity on CemeteryEntity {
  ...CemeterySlugEntity
  attributes {
    title
    address
    openingHoursOverride
  }
}

fragment CemeteryEntity on CemeteryEntity {
  ...CemeteryCardEntity
  attributes {
    type
    description
    contact {
      data {
        ...ContactEntity
      }
    }
    medias {
      data {
        ...UploadImageEntity
      }
    }
    navigateToLink
    latitude
    longitude
    seo {
      ...Seo
    }
  }
}

fragment CemeteryInCeremoniesDebtorsEntity on CemeteryEntity {
  __typename
  id
  attributes {
    title
    localizations {
      data {
        attributes {
          title
          locale
        }
      }
    }
  }
}

fragment BundleCardEntity on BundleEntity {
  __typename
  id
  attributes {
    title
    slug
    perex
    price
    type
    discountTextShort
    discountText
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
    bundleItems {
      description
    }
    additionalItems {
      description
    }
  }
}

fragment BundleEntity on BundleEntity {
  ...BundleCardEntity
  attributes {
    description
    additionalServices {
      id
      title
      description
      price
    }
    documents {
      ...DocumentGroup
    }
    sidebar {
      ...Sidebar
    }
    seo {
      ...Seo
    }
  }
}

fragment BundleSlugEntity on BundleEntity {
  __typename
  id
  attributes {
    slug
    type
    locale
  }
}

fragment ContactEntity on ContactEntity {
  id
  attributes {
    title
    name
    email
    phone1
    phone2
  }
}

fragment DocumentCategoryEntity on DocumentCategoryEntity {
  id
  attributes {
    title
    slug
  }
}

fragment DocumentSlugEntity on DocumentEntity {
  __typename
  id
  attributes {
    slug
    documentCategory {
      data {
        ...DocumentCategoryEntity
      }
    }
  }
}

fragment DocumentCardEntity on DocumentEntity {
  ...DocumentSlugEntity
  attributes {
    title
    publishedAt
    file {
      data {
        ...UploadFileEntity
      }
    }
  }
}

fragment DocumentEntity on DocumentEntity {
  ...DocumentCardEntity
  attributes {
    description
    seo {
      ...Seo
    }
  }
}

fragment GeneralEntity on GeneralEntity {
  attributes {
    header {
      ...Header
    }
    socials {
      ...SocialItem
    }
    contact {
      ...Contact
    }
    footer {
      ...Footer
    }
    generalOpeningHours
  }
}

fragment PartnerEntity on PartnerEntity {
  id
  attributes {
    title
    link
    logo {
      data {
        ...UploadImageEntity
      }
    }
    featured
    priority
  }
}

fragment PageSlugEntity on PageEntity {
  __typename
  attributes {
    slug
    locale
  }
}

fragment PageCardEntity on PageEntity {
  __typename
  id
  attributes {
    title
    slug
    publishedAt
    perex
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment PageEntity on PageEntity {
  ...PageCardEntity
  attributes {
    layout
    ctaButton {
      ...CtaButton
    }
    sidebar {
      ...Sidebar
    }
    seo {
      ...Seo
    }
    sections {
      ... on ComponentSectionsAccordionGroup {
        __typename
        ...AccordionGroup
      }
      ... on ComponentSectionsBranchGroup {
        __typename
        ...BranchGroup
      }
      ... on ComponentSectionsBundleListing {
        __typename
        ...BundleListing
      }
      ... on ComponentSectionsContactGroup {
        __typename
        ...ContactGroup
      }
      ... on ComponentSectionsDivider {
        __typename
        id
        color
      }
      ... on ComponentSectionsDocumentGroup {
        __typename
        ...DocumentGroup
      }
      ... on ComponentSectionsGallery {
        __typename
        id
        title
        medias {
          data {
            ...UploadImageEntity
          }
        }
      }
      ... on ComponentSectionsPartnersSection {
        __typename
        ...PartnersSection
      }
      ... on ComponentSectionsMenuListing {
        __typename
        id
        title
        slug
      }
      ... on ComponentSectionsManualListing {
        __typename
        ...ManualListing
      }
      ... on ComponentSectionsNewsListing {
        __typename
        ...NewsListing
      }
      ... on ComponentSectionsMapSection {
        __typename
        ...MapSection
      }
      ... on ComponentSectionsPublicDisclosureSection {
        __typename
        id
      }
      ... on ComponentSectionsRichtext {
        __typename
        ...RichtextSection
      }
      ... on ComponentSectionsProceduresSection {
        __typename
        id
        title
      }
      ... on ComponentSectionsDebtorsSection {
        __typename
        id
        description
      }
      ... on ComponentSectionsCeremoniesSection {
        __typename
        ...CeremoniesSection
      }
      ... on ComponentSectionsCeremoniesArchiveSection {
        __typename
        id
      }
      ... on ComponentSectionsDocumentsSection {
        __typename
        id
      }
      ... on ComponentSectionsArticleNewsListing {
        __typename
        id
      }
      ... on ComponentSectionsArticlePressListing {
        __typename
        id
      }
      ... on ComponentSectionsReviewListing {
        __typename
        ...ReviewListing
      }
    }
  }
}

fragment ProceduresEntity on ProcedureEntity {
  attributes {
    outsideMedicalFacility {
      ...Procedure
    }
    atMedicalFacility {
      ...Procedure
    }
  }
}

fragment ReviewEntity on ReviewEntity {
  id
  attributes {
    author
    date
    rating
    description
  }
}

fragment CeremonyEntity on CeremonyEntity {
  id
  attributes {
    dateTime
    name
    birthYear
    type
    company
    officiantProvidedBy
    consentForPrivateFields
    cemetery {
      data {
        attributes {
          title
          slug
          localizations {
            data {
              attributes {
                title
                slug
                locale
              }
            }
          }
        }
      }
    }
  }
}

fragment HomepageCeremonyEntity on CeremonyEntity {
  id
  attributes {
    dateTime
    name
    cemetery {
      data {
        attributes {
          slug
          title
          localizations {
            data {
              attributes {
                slug
                title
              }
            }
          }
        }
      }
    }
  }
}
