fragment NavigationItem on NavigationItem {
  id
  title
  path
  type
  related {
    id
    attributes {
      __typename
      ... on Page {
        title
        slug
      }

      ... on Branch {
        title
        slug
      }
    }
  }
  items {
    id
    title
    path
    type
    related {
      id
      attributes {
        __typename

        ... on Page {
          title
          slug
        }

        ... on Branch {
          title
          slug
        }
      }
    }
    items {
      id
      title
      path
      type
      related {
        id
        attributes {
          __typename

          ... on Page {
            title
            slug
          }

          ... on Branch {
            title
            slug
          }
        }
      }
    }
  }
}

fragment PageEntity on PageEntity {
  id
  attributes {
    title
    slug
  }
}
