fragment NavigationItem on NavigationItem {
  id
  title
  path
  type
  related {
    id
    attributes {
      __typename
      ... on Page {
        title
        slug
      }

      ... on Branch {
        title
        slug
      }
    }
  }
  items {
    id
    title
    path
    type
    related {
      id
      attributes {
        __typename

        ... on Page {
          title
          slug
        }

        ... on Branch {
          title
          slug
        }
      }
    }
    items {
      id
      title
      path
      type
      related {
        id
        attributes {
          __typename

          ... on Page {
            title
            slug
          }

          ... on Branch {
            title
            slug
          }
        }
      }
    }
  }
}

fragment CtaButton on ComponentBlocksButtonLink {
  label
  url
  targetBlank
}

fragment Sidebar on ComponentBlocksSidebar {
  title
  text
  ctaButton {
    ...CtaButton
  }
  contact {
    data {
      ...ContactEntity
    }
  }
}

fragment ContactEntity on ContactEntity {
  id
  attributes {
    title
    name
    email
    phone1
    phone2
  }
}

fragment PageEntity on PageEntity {
  id
  attributes {
    title
    slug
    publishedAt
    layout
    description
    ctaButton {
      ...CtaButton
    }
    sidebar {
      ...Sidebar
    }
    sections {
      ... on ComponentSectionsAccordionGroup {
        __typename
        id
        title
        accordions {
          id
          title
          description
        }
      }
      ... on ComponentSectionsRichtext {
        __typename
        id
        markdown
        button {
          label
          url
          targetBlank
        }
      }
    }
  }
}
