fragment FlatNavigationItem on NavigationItem {
  id
  title
  path
  type
  related {
    id
    attributes {
      __typename
      ... on Page {
        title
        slug
      }

      ... on Branch {
        title
        slug
      }
    }
  }
}

fragment NavigationItem on NavigationItem {
  ...FlatNavigationItem
  items {
    ...FlatNavigationItem
    items {
      ...FlatNavigationItem
    }
  }
}

fragment GeneralEntity on GeneralEntity {
  attributes {
    header {
      ...Header
    }
    social {
      ...Social
    }
    contact {
      ...Contact
    }
    footer {
      ...Footer
    }
    generalOpeningHours
  }
}
