query General($locale: I18NLocaleCode!) {
  navigation: renderNavigation(
    navigationIdOrSlug: "main-navigation"
    type: TREE
    menuOnly: false
    locale: $locale
  ) {
    ...NavigationItem
  }
  general(locale: $locale) {
    data {
      ...GeneralEntity
    }
  }
}

query Procedures($locale: I18NLocaleCode!) {
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}

query Partners {
  partners {
    data {
      ...PartnerEntity
    }
  }
}

query News($locale: I18NLocaleCode!) {
  articles(locale: $locale, sort: ["publishedAt:desc"], pagination: { limit: 4 }) {
    data {
      ...ArticleCardEntity
    }
  }
}

query ArticleBySlug($locale: I18NLocaleCode!, $slug: String!) {
  articles(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...ArticleEntity
    }
  }
}

query PageBySlug($locale: I18NLocaleCode!, $slug: String!) {
  pages(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...PageEntity
    }
  }
}

query BranchBySlug($locale: I18NLocaleCode!, $slug: String!) {
  branches(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...BranchEntity
    }
  }
}

query BundleBySlug($locale: I18NLocaleCode!, $slug: String!) {
  bundles(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...BundleEntity
    }
  }
}

query DocumentBySlug($slug: String!) {
  documents(filters: { slug: { eq: $slug } }) {
    data {
      ...DocumentEntity
    }
  }
}

# strapi returns just the default locale if no locale is provided
# easiest way to get all static paths is to ask for all locales sequentially
query ArticlesStaticPaths($locale: I18NLocaleCode) {
  articles(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

query PagesStaticPaths($locale: I18NLocaleCode) {
  pages(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

query BranchesStaticPaths($locale: I18NLocaleCode) {
  branches(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

query BundlesStaticPaths($locale: I18NLocaleCode) {
  bundles(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

query DocumentsStaticPaths {
  documents {
    data {
      id
      attributes {
        slug
      }
    }
  }
}

query HomePage($locale: I18NLocaleCode) {
  homePage(locale: $locale) {
    data {
      attributes {
        featured {
          ...Cta
        }
        sections {
          ... on ComponentSectionsManualListing {
            __typename
            ...ManualListing
          }
          ... on ComponentSectionsNewsListing {
            __typename
            id
            title
          }
          ...ComponentSectionsUpcomingCeremoniesSection
          ... on ComponentSectionsProceduresShortSection {
            __typename
            id
            title
            showMoreButton {
              ...CtaButton
            }
          }
          ... on ComponentSectionsCtaSection {
            __typename
            ...CtaSection
          }
          ... on ComponentSectionsReviewsSection {
            __typename
            id
            title
            # TODO
          }
        }
      }
    }
  }
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}

query HomepageCeremonies($dateTime: DateTime!) {
  ceremonies(
    filters: { dateTime: { gte: $dateTime } }
    sort: ["dateTime:asc"]
    pagination: { limit: 5 }
  ) {
    data {
      id
      attributes {
        dateTime
        name
        branch {
          data {
            attributes {
              slug
              title
              localizations {
                data {
                  attributes {
                    slug
                    title
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

# Temporary, will be replaced by Meilisearch
query Debtors($page: Int!, $search: String) {
  debtors(pagination: { page: $page, pageSize: 20 }, filters: { lastName: { contains: $search } }) {
    data {
      attributes {
        graveSection
        graveNumber
        firstName
        lastName
        birthDate
        deathDate
        branch {
          data {
            attributes {
              title
              slug
              localizations {
                data {
                  attributes {
                    title
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
    meta {
      pagination {
        page
        total
        pageSize
        pageCount
      }
    }
  }
}

query BranchesInCeremonies {
  branches(filters: { allowInCeremonies: { eq: true } }) {
    ...BranchInCeremoniesDebtors
  }
}

query BranchesInDebtors {
  branches(filters: { allowInDebtors: { eq: true } }) {
    ...BranchInCeremoniesDebtors
  }
}

