query General($locale: I18NLocaleCode!) {
  navigation: renderNavigation(
    navigationIdOrSlug: "main-navigation"
    type: TREE
    menuOnly: false
    locale: $locale
  ) {
    ...NavigationItem
  }
  general(locale: $locale) {
    data {
      ...GeneralEntity
    }
  }
}

query Procedures($locale: I18NLocaleCode!) {
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}

query Partners {
  partners(pagination: { limit: -1 }) {
    data {
      ...PartnerEntity
    }
  }
}

query Reviews($locale: I18NLocaleCode!) {
  reviews(locale: $locale, sort: ["date:desc"], pagination: { limit: -1 }) {
    data {
      ...ReviewEntity
    }
  }
}

query News($locale: I18NLocaleCode!) {
  articles(locale: $locale, sort: ["publishedAt:desc"], pagination: { limit: 4 }) {
    data {
      ...ArticleCardEntity
    }
  }
}

query ArticleBySlug($locale: I18NLocaleCode!, $slug: String!) {
  articles(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...ArticleEntity
    }
  }
}

query PageBySlug($locale: I18NLocaleCode!, $slug: String!) {
  pages(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...PageEntity
    }
  }
}

query BranchBySlug($locale: I18NLocaleCode!, $slug: String!) {
  branches(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...BranchEntity
    }
  }
}

query Branches($locale: I18NLocaleCode!) {
  branches(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...BranchEntity
    }
  }
}

query CemeteryBySlug($locale: I18NLocaleCode!, $slug: String!) {
  cemeteries(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...CemeteryEntity
    }
  }
}

query Cemeteries($locale: I18NLocaleCode!) {
  cemeteries(locale: $locale, sort: ["title:asc"], pagination: { limit: -1 }) {
    data {
      ...CemeteryEntity
    }
  }
}

query ManagedObjectBySlug($locale: I18NLocaleCode!, $slug: String!) {
  managedObjects(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...ManagedObjectEntity
    }
  }
}

query ManagedObjects($locale: I18NLocaleCode!) {
  managedObjects(locale: $locale, sort: ["title:asc"], pagination: { limit: -1 }) {
    data {
      ...ManagedObjectEntity
    }
  }
}

query BundleBySlug($locale: I18NLocaleCode!, $slug: String!) {
  bundles(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...BundleEntity
    }
  }
}

query DocumentBySlug($slug: String!) {
  documents(filters: { slug: { eq: $slug } }) {
    data {
      ...DocumentEntity
    }
  }
}

# strapi returns just the default locale if no locale is provided
# easiest way to get all static paths is to ask for all locales sequentially
query ArticlesStaticPaths($locale: I18NLocaleCode) {
  articles(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...ArticleSlugEntity
    }
  }
}

query PagesStaticPaths($locale: I18NLocaleCode) {
  pages(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...PageSlugEntity
    }
  }
}

query BranchesStaticPaths($locale: I18NLocaleCode) {
  branches(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...BranchSlugEntity
    }
  }
}

query BundlesStaticPaths($locale: I18NLocaleCode) {
  bundles(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...BundleSlugEntity
    }
  }
}

query CemeteriesStaticPaths($locale: I18NLocaleCode) {
  cemeteries(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...CemeterySlugEntity
    }
  }
}

query ManagedObjectsStaticPaths($locale: I18NLocaleCode) {
  managedObjects(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...ManagedObjectSlugEntity
    }
  }
}

query DocumentsStaticPaths {
  documents(pagination: { limit: -1 }) {
    data {
      ...DocumentSlugEntity
    }
  }
}

query HomePage($locale: I18NLocaleCode) {
  homePage(locale: $locale) {
    data {
      attributes {
        featured {
          ...Cta
        }
        seo {
          ...Seo
        }
        sections {
          ... on ComponentSectionsManualListing {
            __typename
            ...ManualListing
          }
          ... on ComponentSectionsArticlesManualListing {
            __typename
            ...ArticlesManualListing
          }
          ... on ComponentSectionsNewsListing {
            __typename
            ...NewsListing
          }
          ... on ComponentSectionsUpcomingCeremoniesSection {
            __typename
            ...UpcomingCeremoniesSection
          }
          ... on ComponentSectionsProceduresShortSection {
            __typename
            ...ProceduresShortSection
          }
          ... on ComponentSectionsCtaSection {
            __typename
            ...CtaSection
          }
          ... on ComponentSectionsHomepageReviewsSection {
            __typename
            ...HomepageReviewsSection
          }
        }
      }
    }
  }
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}

query HomepageCeremonies($dateTime: DateTime!) {
  ceremonies(
    filters: { dateTime: { gte: $dateTime } }
    sort: ["dateTime:asc"]
    pagination: { limit: 5 }
  ) {
    data {
      ...HomepageCeremonyEntity
    }
  }
}

query Ceremonies($dateTime: DateTime!, $cemeteryIdFilter: IDFilterInput = {}) {
  ceremonies(
    pagination: { limit: -1 }
    filters: { dateTime: { gte: $dateTime }, cemetery: { id: $cemeteryIdFilter } }
    sort: ["dateTime:asc"]
  ) {
    data {
      ...CeremonyEntity
    }
  }
}

query CemeteriesInCeremonies {
  cemeteries(filters: { allowInCeremonies: { eq: true } }, pagination: { limit: -1 }) {
    data {
      ...CemeteryInCeremoniesDebtorsEntity
    }
  }
}

query CemeteriesInDebtors {
  cemeteries(filters: { allowInDebtors: { eq: true } }, pagination: { limit: -1 }) {
    data {
      ...CemeteryInCeremoniesDebtorsEntity
    }
  }
}

query DocumentCategories {
  documentCategories(pagination: { limit: -1 }) {
    data {
      ...DocumentCategoryEntity
    }
  }
}

query ArticleNewsCategories {
  articleNewsCategories(pagination: { limit: -1 }) {
    data {
      ...ArticleNewsCategoryEntity
    }
  }
}

query ArticlePressCategories {
  articlePressCategories(pagination: { limit: -1 }) {
    data {
      ...ArticlePressCategoryEntity
    }
  }
}

query ArticleJobsCategories {
  articleJobsCategories(pagination: { limit: -1 }) {
    data {
      ...ArticleJobsCategoryEntity
    }
  }
}

query DocumentFiletypes {
  documentFiletypes
}
