query General($locale: I18NLocaleCode!) {
  navigation: renderNavigation(
    navigationIdOrSlug: "main-navigation"
    type: TREE
    menuOnly: false
    locale: $locale
  ) {
    ...NavigationItem
  }
  general(locale: $locale) {
    data {
      ...GeneralEntity
    }
  }
}

query Procedures($locale: I18NLocaleCode!) {
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}

query PageBySlug($locale: I18NLocaleCode!, $slug: String!) {
  pages(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...PageEntity
    }
  }
}

query BranchBySlug($locale: I18NLocaleCode!, $slug: String!) {
  branches(locale: $locale, filters: { slug: { eq: $slug } }) {
    data {
      ...BranchEntity
    }
  }
}

# strapi returns just the default locale if no locale is provided
# easiest way to get all static paths is to ask for all locales sequentially
query PagesStaticPaths($locale: I18NLocaleCode) {
  pages(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

# strapi returns just the default locale if no locale is provided
# easiest way to get all static paths is to ask for all locales sequentially
query BranchesStaticPaths($locale: I18NLocaleCode) {
  branches(locale: $locale) {
    data {
      id
      attributes {
        slug
        locale
      }
    }
  }
}

query HomePage($locale: I18NLocaleCode) {
  homePage(locale: $locale) {
    data {
      attributes {
        featured {
          ...Cta
        }
        sections {
          ... on ComponentSectionsManualListing {
            __typename
            ...ManualListing
          }
          ... on ComponentSectionsNewsListing {
            __typename
            id
            title
            # TODO
          }
          ... on ComponentSectionsCeremoniesSection {
            __typename
            id
            title
            # TODO
          }

          ... on ComponentSectionsProceduresShortSection {
            __typename
            id
            title
            showMoreButton {
              ...CtaButton
            }
          }
          ... on ComponentSectionsCtaSection {
            __typename
            ...CtaSection
          }
          ... on ComponentSectionsReviewsSection {
            __typename
            id
            title
            # TODO
          }
        }
      }
    }
  }
  procedures: procedure(locale: $locale) {
    data {
      ...ProceduresEntity
    }
  }
}
